apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-angular
spec:
  selector:
    matchLabels:
      app: k8s-angular
  template:
    metadata:
      labels:
        app: k8s-angular
    spec:
      containers:
      - name: k8s-angular
        image: k8s-angular
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
